# Generated by Django 4.0 on 2022-01-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seller_cardowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardowner',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
