# Generated by Django 4.0 on 2022-01-09 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_card_ticket_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.ticket'),
            preserve_default=False,
        ),
    ]
